### ISSUE TITLE
Not able to proceed further 

### ISSUE THREAD

**Issue by Zahidfarooq1** [AbrarMehraj/prayer_mode#1]
![Screenshot_2024-09-06-20-54-34-06_6e91f516db722f9a69c4700f72c4e3e2.jpg](https://github.com/user-attachments/assets/4490a9fd-6cc1-42c8-b9d3-d546640308e2)

Getting this error not able to locate my Location 
Device OnePlus 2t 5g
Android version 14.0

**Comment by AbrarMehraj** [comment]
Hi @Zahidfarooq1 
Could you please clear your cache and try again? This might resolve any potential caching issues that could be affecting the current behavior. Let me know if the issue persists!

**Comment by Zahidfarooq1** [comment]
Working fine,

**Comment by AbrarMehraj** [comment]
@Zahidfarooq1 Thanks for the update
